"""empty message

Revision ID: a08fc0778c7e
Revises: 93d32517be21
Create Date: 2021-07-04 15:48:53.249248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08fc0778c7e'
down_revision = '93d32517be21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'content')
    # ### end Alembic commands ###
